apiVersion: apps/v1
kind: Deployment
metadata:
  name: protein-bitirme-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: protein-bitirme
        image: yallic/protein-bitirme
        ports:
        - containerPort: 80
